---
theme: "polymer"

baseurl: "https://golangmontreal.org"
languageCode: "en-CA"
title: "Golang Montréal - #gomtl"

paginate: 10
copyright: "(ɔ) 2015 Copyleft. The #gomtl team."

Multilingual: true
RenderLanguage: en
DefaultContentLang: en
LinkLanguages:
 - en
 - fr

menu:
  - main
  - footer

params:
  author: "gomtl team"
  profile: "images/gomtl-logo-512.png"
  twitter: "GolangMontreal"
  github: "gomtl"
  googleAnalyticsUserID: "UA-72488186-1"

permalinks:
  post: "/:year/:month/:day/:filename/"

MetaDataFormat: "yaml"

---

theme: "polymer"

baseurl: "https://golangmontreal.org"
languageCode: "fr-CA"
title: "Golang Montréal - #gomtl"

paginate: 10
copyright: "(ɔ) 2015 L'équipe #gomtl. Tous droits renversés."

Multilingual: true
RenderLanguage: fr
DefaultContentLang: en
LinkLanguages:
 - en
 - fr

menu:
  - main
  - footer

params:
  author: "gomtl team"
  profile: "images/gomtl-logo-512.png"
  twitter: "GolangMontreal"
  github: "gomtl"
  googleAnalyticsUserID: "UA-72488186-1"

permalinks:
  post: "/:year/:month/:day/:filename/"

MetaDataFormat: "yaml"
---