---
theme: "polymer"

baseurl: "https://fde-mtl.ca"

paginate: 10

MetaDataFormat: "yaml"
defaultContentLang: fr
defaultContentLanguageInSubdir: true

ignoreFiles:
  - "~$"
  - "\\.#"

menu:
  - main
  - footer

Languages:
  fr:
    weight: 1

    title: "FDE Montréal"
    languageCode: "fr-CA"

    copyright: "FDE Montréal © Tous droits réservés 2022"

  en:
    weight: 2

    title: "FDE Montreal"
    languageCode: "en-CA"

    copyright: "Copyright 2022 © FDE Montreal."


params:
  # Number of articles in the "Latest news" section on the front page.
  homepage_news: 3
  author: "FDE"
  profile: "images/logo-small-alpha-fr.png"
  facebook: ""
  # TODO: faire le setup
  #googleAnalyticsUserID: "UA-72488186-1"

permalinks:
  posts: "/:year/:month/:day/:slug/"
